### ISSUE TITLE
Pop-out transparent title-bar

### ISSUE THREAD

**Issue by ruckc** [alexbodogit/AnchorageFX#1]
On the pop-out windows, the text isn't intuitive as the drag location.  In my first attempt at popping the window out the editor window landed on a black background which hid it fairly well.

![image](https://cloud.githubusercontent.com/assets/1426401/12011680/b3ba75d8-aca5-11e5-92e3-a1f4ce33f1dd.png)

**Comment by alexbodogit** [comment]
hello, thanks for the information. it seems that the file resources / Anchorage.css not loaded

**Comment by ruckc** [comment]
I don't know why the stylesheet isn't loading, i'm running Java 8u66.

I was able to get it to load for the primary Scene (but not the floating Scene) by adding,

```
 scene.getStylesheets().add("resources/AnchorageFX.css"); 
```

to the `AnchorageFX_test.java`.  But for some reason the `StyleManager` piece isn't working at least on my OSX machine.

**Comment by alexbodogit** [comment]
Temporary fix: in tests AnchorageSystem.installDefaultStyle(); should be called last and not first.

Thanks Eugene
