### ISSUE TITLE
DockSplitterContainer dividerPositions

### ISSUE THREAD

**Issue by ruckc** [alexbodogit/AnchorageFX#10]
When attempting to build an Eclipse/Netbeans style multiple document interface, it would be beneficial to have access to DockSplitterContainer's set/get DividerPositions.

This would allow resizing of the DockStation (or SubStation) to prioritize the document Pane.

**Comment by ruckc** [comment]
I feel like there is a more elegant solution than just accessing the setter/getter for dividerPositions, but i'm clueless as to what it is.

**Comment by alexbodogit** [comment]
You can use dockNode.dock(station, DockNode.DOCK_POSITION.CENTER, 0.8);

Where 0.8 is percentage (0..1) of splitter's divider

**Comment by ruckc** [comment]
Awesome... thanks

**Comment by alexbodogit** [comment]
Tell me if it's ok 😊

**Comment by ruckc** [comment]
Yes, it is what I was looking for, in a more elegant solution.

**Comment by alexbodogit** [comment]
Thanks
