### ISSUE TITLE
Project needs a build system

### ISSUE THREAD

**Issue by eugener** [alexbodogit/AnchorageFX#2]
It could be either Maven or Gradle. Let me know which one you're ok with and I can provide a PR

**Comment by alexbodogit** [comment]
Pom.xml added for Maven

**Comment by eugener** [comment]
Very nice! Now just make sure you load it and work with it as Maven project.

**Comment by alexbodogit** [comment]
Wow. Great 👍👍👍👍👍

**Comment by alexbodogit** [comment]
thank you for your help. I hope you can continue to make it even better

**Comment by alexbodogit** [comment]
In not expert of Github but you can help me understand. I have to make new features and wanted to know if it is better to create a branch and then merge or commit directly on the master

**Comment by ruckc** [comment]
Depends on preference.  Creating a branch allows long-lived feature
development to not impact the master branch.  Alternatively, the master is
the bleeding edge, and you create branches for each release for backporting
changes.

## 

Curtis Ruck
Anytime: 210-857-1126

**Comment by alexbodogit** [comment]
I understand, and 'as I expected. thank you so much
