### ISSUE TITLE
DockStation.restore(DockNode node) NullPointerException

### ISSUE THREAD

**Issue by ruckc** [alexbodogit/AnchorageFX#8]
In trying a single DockNode on a DockStation, I pressed maximize button twice, on the second press, it invoked `restore(DockNode node)`.  I got a NPE at line 190, panelParent is null.

Not sure the best approach to solve, as it was technically already maximized, so should the maximized be disabled?  Or should the restore() have a != null check.

Either way, please keep up the good work, it is highly appreciated.

**Comment by alexbodogit** [comment]
Thanks ruckc. you're right, the button should be disabled. I will solve the problem immediately

**Comment by alexbodogit** [comment]
I think I've solved, tell me what you think. Thanks again for your contribution

**Comment by alexbodogit** [comment]
Inviato da iPhone

Il giorno 02 gen 2016, alle ore 02:37, Curtis Ruck <notifications@github.com<mailto:notifications@github.com>> ha scritto:

In trying a single DockNode on a DockStation, I pressed maximize button twice, on the second press, it invoked restore(DockNode node). I got a NPE at line 190, panelParent is null.

Not sure the best approach to solve, as it was technically already maximized, so should the maximized be disabled? Or should the restore() have a != null check.

Either way, please keep up the good work, it is highly appreciated.

##

**Comment by ruckc** [comment]
Looks good, it addresses the issue I ran into.
